#         __            _______                             __                        __
#        |  \          |       \                           |  \                      |  \
#    ____| $$  ______  | $$$$$$$\  ______    ______    ____| $$ __    __   _______  _| $$_
#   /      $$ /      \ | $$__/ $$ /      \  /      \  /      $$|  \  |  \ /       \|   $$ \
#  |  $$$$$$$|  $$$$$$\| $$    $$|  $$$$$$\|  $$$$$$\|  $$$$$$$| $$  | $$|  $$$$$$$ \$$$$$$
#  | $$  | $$| $$    $$| $$$$$$$ | $$   \$$| $$  | $$| $$  | $$| $$  | $$| $$        | $$ __
#  | $$__| $$| $$$$$$$$| $$      | $$      | $$__/ $$| $$__| $$| $$__/ $$| $$_____   | $$|  \
#   \$$    $$ \$$     \| $$      | $$       \$$    $$ \$$    $$ \$$    $$ \$$     \   \$$  $$
#    \$$$$$$$  \$$$$$$$ \$$       \$$        \$$$$$$   \$$$$$$$  \$$$$$$   \$$$$$$$    \$$$$
#
# Социальные ссылки
# Telegram: @d31zy_
# Discord: kraken.su

messages:
  # Сообщение когда игрок пытается поставить эндер-сундук в режиме пвп
  on-place: "&#CD1818[🗡] &fК сожалению, но вы &#CD1818не можете&f ставить &#CD1818Эндер Сундук&f в режиме &#CD1818PvP!"
  # Сообщение когда игрок пытается использовать эндер-сундук в режиме пвп
  on-interact: "&#CD1818[🗡] &fК сожалению, но вы &#CD1818не можете&f использовать &#CD1818Эндер Сундук&f в режиме &#CD1818PvP!"

