name: deAntiRelogEC
version: '${project.version}'
main: ru.dercec.plugin.deantirelogec.deAntiRelogEC
api-version: '1.16'
depend: [powerantirelog]

commands:
  deantirelogec:
    description: "Перезагружает конфиг"